Repository ablecloud-team/ablestack-genie, pull requests merged in 2022-10, with the labels that each got.

#14 Genie에서 배포되는 VM의 "오퍼링 명" 변경
  playbook/template/template_deploy.yml
Labels: bug

#15 배포서비스 가상머신 오퍼링명 및 playbook 소스url 변경
  genie-shell/automation_controller_template/deploy_automation_controller.yml
  playbook/eGovFrame/eGov_deploy.yml
  playbook/nextcloud/nextcloud_deploy.yml
  playbook/template/template_deploy.yml
  playbook/wordpress/wordpress_deploy.yml
Labels: bug, enhancement

#16 Genie Git 프로젝트 생성시 git branch명 변경
  genie-shell/automation_controller_template/deploy_automation_controller.yml
Labels: enhancement
